### ISSUE TITLE
Why use "//" instead of "/* ... */" for Java and Kotlin?

### ISSUE THREAD

**Issue by fstanis** [google/addlicense#65] opened 2021-03-25 12:20 UTC
It seems the majority of Java projects puts the license on top of the file via multiple comments `/* ... */`, but `addlicense` uses `//` for Java and Kotlin:

https://github.com/google/addlicense/blob/a0294312aa76d31c0bd7e49083d88a2a04d9b3d1/main.go#L220-L221

Is there any reason for this? If not, I think we should move `.java`, `.kt` and `.kts` a few lines above with other languages that use `/* ... */`.

**Comment by willnorris** [comment] 2021-08-09 22:24
Closing as duplicate of #46, and will continue discussion there.

**Closed by willnorris** 2021-08-09 22:24 UTC
